#    .------..------..------..------..------..------..------..------..------..------..------..------.
#    |P.--. ||I.--. ||X.--. ||E.--. ||L.--. ||C.--. ||R.--. ||A.--. ||S.--. ||H.--. ||E.--. ||R.--. |
#    | :/\: || (\/) || :/\: || (\/) || :/\: || :/\: || :(): || (\/) || :/\: || :/\: || (\/) || :(): |
#    | (__) || :\/: || (__) || :\/: || (__) || :\/: || ()() || :\/: || :\/: || (__) || :\/: || ()() |
#    | '--'P|| '--'I|| '--'X|| '--'E|| '--'L|| '--'C|| '--'R|| '--'A|| '--'S|| '--'H|| '--'E|| '--'R|
#    `------'`------'`------'`------'`------'`------'`------'`------'`------'`------'`------'`------'
#                                                                                  by PixelCrack3r

developer:
  debug:
    showLoaders: false
    debugListener: false
    reloadAddonsOnChange: false